// Code generated by MockGen. DO NOT EDIT.
// Source: room.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	model "github.com/ari1021/websocket/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIRoom is a mock of IRoom interface
type MockIRoom struct {
	ctrl     *gomock.Controller
	recorder *MockIRoomMockRecorder
}

// MockIRoomMockRecorder is the mock recorder for MockIRoom
type MockIRoomMockRecorder struct {
	mock *MockIRoom
}

// NewMockIRoom creates a new mock instance
func NewMockIRoom(ctrl *gomock.Controller) *MockIRoom {
	mock := &MockIRoom{ctrl: ctrl}
	mock.recorder = &MockIRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRoom) EXPECT() *MockIRoomMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockIRoom) Create(name string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIRoomMockRecorder) Create(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRoom)(nil).Create), name)
}

// FindAll mocks base method
func (m *MockIRoom) FindAll() (*model.Rooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(*model.Rooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockIRoomMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIRoom)(nil).FindAll))
}

// Delete mocks base method
func (m *MockIRoom) Delete(id uint) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockIRoomMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRoom)(nil).Delete), id)
}
